name: bio-ilastik
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - conda-build
  - mypy
  - pytest
  - python >=3.7
  - xarray
  - pytorch
  - cpuonly
  - onnxruntime
  - tensorflow
  - pip
  # bioimageio dependencies; to be removed when using conda packages:
  - marshmallow < 4.0
  - marshmallow-jsonschema
  - marshmallow-union
  - ruamel.yaml
  - requests
  - typer
  - typing-extensions
  - pip:
    - git+https://github.com/bioimage-io/spec-bioimage-io.git@better_exception_for_validate
    - git+https://github.com/bioimage-io/core-bioimage-io-python.git@add_test_resource
