name: bio-core-mix
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bioimageio.core >=0.4.3; <0.5
  - cpuonly
  - onnxruntime
  - python >=3.7
  - pytorch
  - tensorflow
  - tqdm  # todo: remove; missing dep in bioimageio.core 0.4.3; fixed on main already
