name: auto-update

on:
  pull_request:
    branches: [ main ]

jobs:
  get-pending:
    runs-on: ubuntu-latest
    outputs:
      pending_matrix: ${{ steps.get_pending.outputs.pending_matrix }}
      has_pending_matrix: ${{ steps.get_pending.outputs.has_pending_matrix }}

    steps:
    - uses: actions/checkout@v2
    - name: install script deps
      run: pip install typer ruamel.yaml requests
    - name: get pending
      id: get_pending
      run: python scripts/get_pending_validations.py --branch ${{ github.event.pull_request.head.ref }}
    - name: debug found pending ${{ steps.get_pending.outputs.has_pending_matrix }}
      run: echo ${{ steps.get_pending.outputs.pending_matrix }}

  validate:
    needs: get-pending
    uses: bioimage-io/collection-bioimage-io/.github/workflows/validate_resources.yaml@main
    with:
      pending_matrix: ${{ needs.get-pending.outputs.pending_matrix }}
      has_pending_matrix: ${{ needs.get-pending.outputs.has_pending_matrix }}
      check_validation: 'yes'
