name: auto-update

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    if: needs.update-rdfs.outputs.has_pending_matrix_bioimageio == 'yes'
    uses: fynnbe/collection-bioimage-io/.github/workflows/validate_resources.yaml@main  # todo: change orga to bioimage-io
    with:
      check_validation: 'yes'
      deploy_to: 'preview'

  delete-bot-comments:
    runs-on: ubuntu-latest
    steps:
    - uses: izhangzhihao/delete-comment@master
      continue-on-error: true  # there might not be a comment yet
      with:
        github_token: ${{ secrets.PAT }}
        delete_user_name: bioimageiobot
        issue_number: ${{ github.event.number }}
