name: auto-update

on:
  pull_request:
    branches: [ main ]

jobs:
  get-pending:
    runs-on: ubuntu-latest
    outputs:
      pending_matrix: ${{ steps.pending.outputs.pending_matrix }}
      has_pending_matrix: ${{ steps.pending.outputs.has_pending_matrix }}

    steps:
    - uses: actions/checkout@v2
    - name: install script deps
      run: pip install typer bioimageio.spec requests lxml
    - name: update rdfs
      id: pending
      run: python scripts/update_rdfs.py --branch ${{ github.event.pull_request.head.ref }}
    - name: debug found pending ${{ steps.pending.outputs.has_pending_matrix }}
      run: echo ${{ steps.pending.outputs.pending_matrix }}
    - name: "Upload updated rdfs as 'updated_rdfs'"
      uses: actions/upload-artifact@v2
      with:
        name: updated_rdfs
        path: dist
        retention-days: 1

  validate:
    needs: get-pending
    uses: fynnbe/collection-bioimage-io/.github/workflows/validate_resources.yaml@main  # todo: change orga to bioimage-io
    with:
      pending_matrix: ${{ needs.get-pending.outputs.pending_matrix }}
      has_pending_matrix: ${{ needs.get-pending.outputs.has_pending_matrix }}
      check_validation: 'yes'
      download_updated_rdfs: 'yes'
      deploy_to: 'preview'

  hide-comments:
    runs-on: ubuntu-latest
    steps:
    - uses: kanga333/comment-hider@master
      name: Hide bot comments
      continue-on-error: true  # there might not be a comment yet
      with:
        github_token: ${{ secrets.PAT }}
        hide_user_name: bioimageiobot
