# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.

  update-collection-validation:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]  # todo: make matrix with pytorch/tensorflow/onnx envs instead of the one dev env
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-dev
        environment-file: dev/environment-base.yaml
        python-version: ${{ matrix.python-version }}
    - name: update collection test for ${{ matrix.python-version }}
      run: python scripts/update_collection_validation.py dist/rdf.yaml dist/validation_summary.yaml
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
