# This workflow will gather the BioImage.IO resource collection from zenodo using node, then validate the collected
# resources and publish the validation summaries on the gh-pages branch

name: Validate BioImage.IO collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-collection:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Check for pending
      run: npm run check-pending
