name: post PR

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  check_for_new_resources:
    if: github.event.pull_request.merged == false  # if true we trigger via merge commit
    uses: fynnbe/collection-bioimage-io/.github/workflows/collection_main.yaml@main  # todo: change orga to bioimage-io
