name: post PR

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  check_for_new_resources:
    if: github.event.pull_request.merged == false  # if true we trigger via merge commit
    uses: bioimage-io/collection-bioimage-io/.github/workflows/auto_update_main.yaml@main
