name: Reset last_ci_run tag

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.x
      with:
        route: POST /repos/${{ github.repository }}/git/refs/tags/last_ci_run
        sha: ${{ github.sha }}
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
