name: Reset partner test summaries

# we might have to make this wf callable and split the workflow_dispatch up, such that parallel partner resets do not lead to skipped resets
concurrency: main  # do not run this workflow in parallel with the main ci

on:
  workflow_dispatch:
    inputs:
      partner_id:
        description: partner id (github orga)
        type: string
        required: true

jobs:
  reset_test_summaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: install script deps
      run: pip install typer bioimageio.spec
    - name: reset test summaries
      run: python scripts/reset_partner_test_summaries.py ${{ matrix.partner_id }}
    - name: Deploy to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        clean: false
        folder: dist
