name: Trigger partner workflows

on:
  workflow_call:
    inputs:
      pending_matrix:
        description: json string of gh matrix (to be used with fromJson())
        type: string
        required: false
        default: '{"include": [{"resource_id": "rid", "version_id": "vid", "partner_id": "all"}]}'
    secrets:
      PAT:
        required: true

jobs:
  trigger_partners:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - partner_id: ilastik
          owner: ilastik
          repo: bioimage-io-resources
          workflow: test_bioimageio_resources.yaml

    steps:
    - uses: actions/checkout@v2
    - name: find partner ids
      id: prep
      run: |
        python -c 'import json;incl=json.loads('"'"'${{ inputs.pending_matrix }}'"'"')["include"];print(f"::set-output name=partner_ids::{list(set([ic['"'"'partner_id'"'"'] for ic in incl]))}")'
    - name: debug
      run: echo ${{ secrets.PAT }}
    - uses: octokit/request-action@v2.x
      env:
        GITHUB_TOIKEN: ${{ secrets.PAT }}
      with:
        route: POST /repos/${{ matrix.owner }}/${{ matrix.repo }}/actions/workflows/${{ matrix.workflow }}/dispatches
        ref: refs/heads/main
        inputs: '{"pending_matrix": ''${{ inputs.pending_matrix }}'''
        GITHUB_TOIKEN: ${{ secrets.PAT }}
