name: Trigger partner workflows

on:
  workflow_call:
    inputs:
      pending_matrix:
        description: json string of gh matrix (to be used with fromJson())
        type: string
        required: false
        default: '{"include": [{"resource_id": "rid", "version_id": "vid", "partner_id": "all"}]}'

jobs:
  trigger_partners:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - partner_id: ilastik
          owner: ilastik
          repo: bioimage-io-resources
          workflow: test BioImage.IO resources

    steps:
    - uses: actions/checkout@v2
    - name: find partner ids
      id: prep
      run: |
        python -c 'import json;incl=json.loads('"'"'${{ inputs.pending_matrix }}'"'"')["include"];print(f"::set-output name=partner_ids::{list(set([ic['"'"'partner_id'"'"'] for ic in incl]))}")'
    - name: debug partner ids
      run: echo '${{ steps.prep.outputs.partner_ids }}'
    - name: install script deps
      if: contains(steps.prep.outputs.partner_ids, matrix.partner_id) || contains(steps.prep.outputs.partner_ids, 'all')
      run: pip install typer PyGithub
    - name: trigger ${{ matrix.partner_id }}
      if: contains(steps.prep.outputs.partner_ids, matrix.partner_id) || contains(steps.prep.outputs.partner_ids, 'all')
      run: python scripts/trigger_partner_wf.py '${{ inputs.pending_matrix }}' --owner ${{ matrix.owner || matrix.partner_id }} --repo ${{ matrix.repo }} --workflow '${{ matrix.workflow }}' --pat ${{ secrets.PAT }}
    - name: debug
      run: |
        echo '1 ${{ matrix.nothing || 'my string' }}'
