name: Trigger partner workflows

on:
  workflow_call:
    inputs:
      pending_matrix:
        description: json string of gh matrix (to be used with fromJson())
        type: string
        required: false
        default: '{"include": [{"resource_id": "rid", "version_id": "vid"}]}'

jobs:
  trigger_partners:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - owner: ilastik
          repo: bioimage-io-resources
          workflow: test_bioimageio_resources.yaml

    steps:
    - name: escape json matrix string
      id: escape_json
      run: |
        python -c 'import json;s='"'"'${{ inputs.pending_matrix }}'"'"';print(f"::set-output name=escaped::{json.dumps(s)}")'
    - name: trigger ${{ matrix.owner }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: validate BioImage.IO resources
        repo: ${{ matrix.owner }}/${{ matrix.repo }}
        token: ${{ secrets.PAT }}
        inputs: '{"pending_matrix": ${{ steps.escape_json.outputs.escaped }}}'
