# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate BioImage.IO collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 */2 * * *'


jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]

    outputs:
      dist: ${{ steps.get_dist.outputs.dist }}

    steps:
    - uses: actions/checkout@v2
    - name: Get dist folder
      id: get_dist
      shell: bash
      run: |
        echo "Pull request's base branch is: ${{ github.head_ref }}"
        if github.event_name == 'pull_request'; then dist=${{ github.head_ref }}; else dist=gh-pages; fi
        echo "::set-output name=dist::$dist"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: copy generated files to branch sepcific dist folder
      shell: bash
      run: mkdir ${{ steps.get_dist.outputs.dist }}; cp npm-dist/* ${{ steps.get_dist.outputs.dist }}

  validate-ilastik:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        weights-format: [onnx]

    needs: setup
    steps:
    - uses: actions/checkout@v2
    - name: install validation dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-spec
        environment-file: dev/environment-ilastik.yaml
        python-version: ${{ matrix.python-version }}
    - name: validate for ${{ matrix.python-version }} ${{ matrix.weights-format }}
      shell: bash -l {0}
      run: python scripts/generate_collection_test_summary.py ${{ needs.setup.outputs.dist }}/rdf.yaml ${{ needs.setup.outputs.dist }}/validation_summaries/ilastik/${{ matrix.python-version }}_${{ matrix.weights-format }}.yaml ${{ matrix.weights-format }}

  deploy:
    runs-on: ubuntu-latest

    needs: [setup, validate-ilastik]
    steps:
    - name: Inspect dist folder
      shell: bash -l {0}
      run: |
        ls ${{ needs.setup.outputs.dist }}
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${{ needs.setup.outputs.dist }}  # The branch the action should deploy to.
        folder: ${{ needs.setup.outputs.dist }}  # The folder the action should deploy.
