# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate BioImage.IO collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 */2 * * *'
jobs:
  fetch-collection:
    env:
      dist: main-dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]

    steps:
    - uses: actions/checkout@v2
    - name: Get pull request's base branch
      if: github.event_name == 'pull_request'
      run: |
        echo "Pull request's base branch is: ${{ github.head_ref }}"
      env:
        dist: ${{ github.head_ref }}-dist

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: copy generated files to branch sepcific dist folder
      shell: bash
      run: mkdir ${{ env.dist }}; cp npm-dist/* ${{ env.dist }}
    - name: Deploy 🚀
      if: ${{ steps.extract_branch.outputs.branch }} == main
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: npm-dist  # The folder the action should deploy.

  validate-ilastik:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        weights-format: [onnx]

    needs: fetch-collection
    steps:
    - uses: actions/checkout@v2
    - name: install validation dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-spec
        environment-file: dev/environment-ilastik.yaml
        python-version: ${{ matrix.python-version }}
    - name: validate for ${{ matrix.python-version }} ${{ matrix.weights-format }}
      shell: bash -l {0}
      run: python scripts/update_collection_validation.py ${{ env.dist }}/rdf.yaml ${{ env.dist }}/validation_summaries/ilastik/${{ matrix.python-version }}_${{ matrix.weights-format }}.yaml

  deploy-validation-summaries:
    runs-on: ubuntu-latest

    needs: [validate-ilastik]
    steps:
    - name: Inspect dist folder
      shell: bash -l {0}
      run: |
        ls ${{ env.dist }}
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${{ env.dist }}  # The branch the action should deploy to.
        folder: ${{ env.dist }}  # The folder the action should deploy.
